# Checks that has to pass before merge to devel can be done
status = [
  "All check passed",
  "Reproducibility tests"
]

# Checks that has to pass before bors will process the PR
pr_status = [
  "PR has only one commit"
]

# When turning PR into commit message, consider the body ends at the first
# thematic break.
cut_body_after = "---"
